services:
  app:
    build: .
    image: ss-translate:local
    container_name: ss-translate
    
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=
      - SERVER_PORT=8080
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - USE_REDIS_UNSECURE = "yep" # set this to any non-empty string to use non-TLS connection to redis.
    volumes:
      - ./credentials.json:/app/credentials.json:ro
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  redis-data:
